// ATX Let's Play — Real Austin Courts Seed Data
// Source: Austin Parks & Recreation public data + field research
// Run this script once to populate Firestore with real court data.

import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc, serverTimestamp } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY,
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.VITE_FIREBASE_APP_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

export const AUSTIN_COURTS = [
  // ─── MUELLER ───────────────────────────────────────────────
  {
    id: 'mueller-basketball-rec',
    name: 'Mueller Rec Center Courts',
    shortName: 'Mueller Rec',
    district: 'mueller',
    sport: ['basketball'],
    address: '4729 Mueller Blvd, Austin, TX 78723',
    coords: { lat: 30.2974, lng: -97.7058 },
    surface: 'concrete',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['water fountain', 'restrooms', 'parking', 'shade'],
    courtCount: 4,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Four full outdoor basketball courts at Mueller Rec Center. Well-maintained with lighting for evening games.',
    googleMapsUrl: 'https://maps.google.com/?q=Mueller+Rec+Center+Austin+TX',
    filmingPriority: 1,
  },
  {
    id: 'mueller-petanque',
    name: 'Mueller Park Pétanque Court',
    shortName: 'Mueller Pétanque',
    district: 'mueller',
    sport: ['petanque'],
    address: 'Mueller Lake Park, Austin, TX 78723',
    coords: { lat: 30.2981, lng: -97.7041 },
    surface: 'gravel',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['nearby restrooms', 'parking', 'shade trees', 'lake view'],
    courtCount: 2,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Two dedicated pétanque courts at Mueller Lake Park. One of Austin\'s finest boules venues with a beautiful lake backdrop.',
    googleMapsUrl: 'https://maps.google.com/?q=Mueller+Lake+Park+Petanque+Austin+TX',
    filmingPriority: 1,
  },
  {
    id: 'mueller-soccer',
    name: 'Mueller Park Soccer Fields',
    shortName: 'Mueller Soccer',
    district: 'mueller',
    sport: ['soccer'],
    address: 'Mueller Neighborhood Park, Austin, TX 78723',
    coords: { lat: 30.2968, lng: -97.7052 },
    surface: 'grass',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['parking', 'restrooms', 'water fountain'],
    courtCount: 2,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Two grass soccer fields in the Mueller neighborhood. Great for pickup games and community leagues.',
    googleMapsUrl: 'https://maps.google.com/?q=Mueller+Park+Soccer+Austin+TX',
    filmingPriority: 2,
  },
  {
    id: 'sunday-market-petanque',
    name: 'Sunday Market Pétanque Court',
    shortName: 'SFC Pétanque',
    district: 'mueller',
    sport: ['petanque'],
    address: '4209 Airport Blvd, Austin, TX 78722',
    coords: { lat: 30.3012, lng: -97.7089 },
    surface: 'gravel',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['farmers market nearby', 'food vendors', 'parking'],
    courtCount: 1,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Pétanque court adjacent to the Sustainable Food Center Farmers Market. Active Sunday morning scene with dedicated players.',
    googleMapsUrl: 'https://maps.google.com/?q=SFC+Farmers+Market+Pétanque+Austin',
    filmingPriority: 1,
  },

  // ─── HYDE PARK ─────────────────────────────────────────────
  {
    id: 'ramsey-park-basketball',
    name: 'Ramsey Park Basketball Courts',
    shortName: 'Ramsey Park',
    district: 'hyde-park',
    sport: ['basketball'],
    address: '1112 W 29th St, Austin, TX 78705',
    coords: { lat: 30.2964, lng: -97.7415 },
    surface: 'concrete',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['water fountain', 'restrooms', 'tennis courts nearby', 'parking'],
    courtCount: 2,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Classic Hyde Park basketball courts. Popular for pickup games with a great neighborhood atmosphere.',
    googleMapsUrl: 'https://maps.google.com/?q=Ramsey+Park+Austin+TX',
    filmingPriority: 2,
  },
  {
    id: 'ramsey-park-tennis',
    name: 'Ramsey Park Tennis Courts',
    shortName: 'Ramsey Tennis',
    district: 'hyde-park',
    sport: ['tennis', 'pickleball'],
    address: '1112 W 29th St, Austin, TX 78705',
    coords: { lat: 30.2962, lng: -97.7413 },
    surface: 'hard',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['water fountain', 'restrooms', 'shaded seating', 'parking'],
    courtCount: 4,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Four hard courts at Ramsey Park. Used for both tennis and pickleball. Free and open to the public.',
    googleMapsUrl: 'https://maps.google.com/?q=Ramsey+Park+Tennis+Austin+TX',
    filmingPriority: 3,
  },

  // ─── ZILKER / NORWOOD ──────────────────────────────────────
  {
    id: 'zilker-volleyball',
    name: 'Zilker Park Sand Volleyball',
    shortName: 'Zilker Volleyball',
    district: 'norwood',
    sport: ['volleyball'],
    address: 'Zilker Metropolitan Park, Austin, TX 78746',
    coords: { lat: 30.2671, lng: -97.7724 },
    surface: 'sand',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'Barton Springs nearby', 'food trucks nearby'],
    courtCount: 6,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Six sand volleyball courts at iconic Zilker Park. Austin\'s most popular outdoor volleyball spot with stunning downtown views.',
    googleMapsUrl: 'https://maps.google.com/?q=Zilker+Park+Volleyball+Austin+TX',
    filmingPriority: 2,
  },
  {
    id: 'zilker-soccer',
    name: 'Zilker Park Soccer Fields',
    shortName: 'Zilker Soccer',
    district: 'norwood',
    sport: ['soccer'],
    address: 'Zilker Metropolitan Park, Austin, TX 78746',
    coords: { lat: 30.2678, lng: -97.7698 },
    surface: 'grass',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'water fountain'],
    courtCount: 4,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Multiple grass soccer fields at Zilker Park. Wide open spaces perfect for pickup matches in a beautiful setting.',
    googleMapsUrl: 'https://maps.google.com/?q=Zilker+Park+Soccer+Austin+TX',
    filmingPriority: 3,
  },

  // ─── DOWNTOWN ──────────────────────────────────────────────
  {
    id: 'fiesta-gardens',
    name: 'Fiesta Gardens Multi-Sport',
    shortName: 'Fiesta Gardens',
    district: 'downtown',
    sport: ['soccer', 'volleyball'],
    address: '2101 Jesse E Segovia St, Austin, TX 78702',
    coords: { lat: 30.2605, lng: -97.7231 },
    surface: 'grass',
    lights: false,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'lake view', 'pavilion'],
    courtCount: 3,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Multi-sport complex on Lady Bird Lake. Soccer fields and volleyball courts with beautiful waterfront views.',
    googleMapsUrl: 'https://maps.google.com/?q=Fiesta+Gardens+Austin+TX',
    filmingPriority: 2,
  },

  // ─── EAST AUSTIN ───────────────────────────────────────────
  {
    id: 'govalle-park',
    name: 'Govalle Neighborhood Park',
    shortName: 'Govalle Park',
    district: 'east',
    sport: ['basketball', 'soccer'],
    address: '5200 Bolm Rd, Austin, TX 78702',
    coords: { lat: 30.2591, lng: -97.6960 },
    surface: 'concrete',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'baseball diamond', 'playground'],
    courtCount: 3,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'East Austin community park with basketball courts and soccer fields. A hub for the local East Austin sports community.',
    googleMapsUrl: 'https://maps.google.com/?q=Govalle+Park+Austin+TX',
    filmingPriority: 3,
  },

  // ─── SOUTH CONGRESS ────────────────────────────────────────
  {
    id: 'garrison-park-basketball',
    name: 'Garrison Park Basketball',
    shortName: 'Garrison Park',
    district: 'south-congress',
    sport: ['basketball'],
    address: '6001 Manchaca Rd, Austin, TX 78745',
    coords: { lat: 30.2241, lng: -97.7895 },
    surface: 'concrete',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'water fountain', 'skate park nearby'],
    courtCount: 2,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Popular South Austin basketball courts at Garrison Park. Evening games are a staple for the South Congress community.',
    googleMapsUrl: 'https://maps.google.com/?q=Garrison+Park+Austin+TX',
    filmingPriority: 3,
  },

  // ─── NORTH AUSTIN ──────────────────────────────────────────
  {
    id: 'northwest-disc-golf',
    name: 'Shoal Creek Disc Golf Course',
    shortName: 'Shoal Creek DG',
    district: 'north',
    sport: ['disc-golf'],
    address: 'Shoal Creek Greenbelt, Austin, TX 78756',
    coords: { lat: 30.3202, lng: -97.7485 },
    surface: 'grass/trail',
    lights: false,
    indoor: false,
    accessibility: false,
    amenities: ['free parking', 'trail access', 'greenbelt'],
    courtCount: 18,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: '18-hole disc golf course through the Shoal Creek Greenbelt. One of Austin\'s most scenic and challenging courses.',
    googleMapsUrl: 'https://maps.google.com/?q=Shoal+Creek+Disc+Golf+Austin+TX',
    filmingPriority: 4,
  },
  {
    id: 'north-austin-softball',
    name: 'Westenfield Park Baseball',
    shortName: 'Westenfield Park',
    district: 'north',
    sport: ['baseball', 'softball'],
    address: '3808 Steck Ave, Austin, TX 78759',
    coords: { lat: 30.3610, lng: -97.7482 },
    surface: 'dirt/grass',
    lights: true,
    indoor: false,
    accessibility: true,
    amenities: ['restrooms', 'parking', 'dugouts', 'concession stand'],
    courtCount: 2,
    status: 'active',
    modelUrl: null,
    thumbnailUrl: null,
    photos: [],
    description: 'Well-maintained baseball and softball diamonds at Westenfield Park. Lighted for evening leagues and pickup games.',
    googleMapsUrl: 'https://maps.google.com/?q=Westenfield+Park+Austin+TX',
    filmingPriority: 4,
  },
];

// ─── Seed Function ────────────────────────────────────────────────────────────
async function seedCourts() {
  console.log(`🏀 Seeding ${AUSTIN_COURTS.length} Austin courts to Firestore...`);
  for (const court of AUSTIN_COURTS) {
    const { id, ...data } = court;
    await setDoc(doc(db, 'courts', id), {
      ...data,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
    console.log(`  ✅ ${court.name}`);
  }
  console.log('🎉 All courts seeded!');
}

seedCourts().catch(console.error);
